# Generated by Django 2.2.12 on 2021-05-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai_kemampuan_komunikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(max_length=20)),
                ('bobot', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai_kesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(max_length=20)),
                ('bobot', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai_prestasi_kerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.IntegerField(max_length=20)),
                ('bobot', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_kerja', models.IntegerField(max_length=50)),
                ('usia', models.IntegerField(max_length=50)),
                ('kemampuan_komunikasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikasi.Nilai_kemampuan_komunikasi')),
                ('kesehatan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikasi.Nilai_kesehatan')),
                ('prestasi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikasi.Nilai_prestasi_kerja')),
            ],
        ),
    ]
