# Generated by Django 2.2.12 on 2021-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='masa_kerja',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='usia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai_kemampuan_komunikasi',
            name='bobot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai_kemampuan_komunikasi',
            name='nilai',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nilai_kesehatan',
            name='bobot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai_kesehatan',
            name='nilai',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='nilai_prestasi_kerja',
            name='bobot',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai_prestasi_kerja',
            name='nilai',
            field=models.CharField(max_length=20),
        ),
    ]
