# Generated by Django 2.2.12 on 2021-05-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikasi', '0002_auto_20210523_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
